--rollback
USE master;
ALTER DATABASE DislogDWH SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
RESTORE DATABASE DislogDWH
FROM DISK = 'C:\SQLData\DislogDWH_backup_before_fix.bak'
WITH REPLACE;
ALTER DATABASE DislogDWH SET MULTI_USER;